version: '3.9'
services:
    vuln-nodejs:
        build:
            context: .
        container_name: vuln-nodejs
        ports:
         - "5000:5000"
        env_file: .env
        environment:
         - DATABASE_URL=/db/sqlite.db 
        